### ISSUE TITLE
"New" Supabase auth ssr package

### ISSUE THREAD

**Issue by CharlBest** [CriticalMoments/CMSaasStarter#29]
Amazing project! Exactly what I was looking for.

Curious what are your thoughts on the `@supabase/ssr` package rather than using `auth-helpers`?
It seems going forward that it is the package that will get the updates and be maintained. That said, I'm not sure if there are differences now so wouldn't have an influence at this stage, right?

<img width="937" alt="image" src="https://github.com/CriticalMoments/CMSaasStarter/assets/6147400/f4f914b9-8517-4567-8e72-bb6aecc9ea3f">

Saw a [YouTuber do the migration](https://www.youtube.com/watch?v=nk4LTSy7XtA&ab_channel=BenDavis), if you are interested.

**Comment by scosman** [comment]
I looked at this, but honestly I can't remember why I didn't migrate. I'd want to keep the CSR option because svelte does such a good job of it. Would be curious if SSR can run in CSR for sveltekit.

P2 nice to have. No bug per se, but keeping up with times always good.

We've had issues with auth-helpers: https://github.com/CriticalMoments/CMSaasStarter/commit/9211be0afccc82aa3916dcd9206a204ee092d742

**Comment by owenversteeg** [comment]
I think it'd be good to migrate, as Supabase seems to be phasing out the auth-helpers stuff pretty aggressively and providing less support and attention there. Maybe something to add to your todo list from your other issue @CharlBest? :)

**Comment by kizivat** [comment]
I just migrated in my fork but I still get some supabase warnings about using `user` object from the unsafe `getSession()` which I cannot pin-point where they are occurring exactly.

**Comment by scosman** [comment]
Finallllly done: https://github.com/CriticalMoments/CMSaasStarter/pull/135
