### ISSUE TITLE
Some production things

### ISSUE THREAD

**Issue by Pluriscient** [CriticalMoments/CMSaasStarter#62]
Thank you for the lovely template. Currently using it for a (currently) closed-source app, but wanted to share some things we ran into while adjusting this for our production use-case. 

- Resetting the password broke at some point as the `amr` token didn't seem to be set. 
- Supabase auth has some updates that spam warnings when using the getsession method on the server side [like here](https://github.com/supabase/auth-js/issues/873). Should be fixed in a new version now.
- Discounts. Applying discounts is a common thing but not trivial with the current pricing scheme system (as far as we could see)
- Company name and website name should be optional when creating an account
- We switched most forms to using superforms to make validation a bit clearer on the DX side (particularly for optional elements)

Happy to expand on things if requested. We're still in the process of smoothing out some bugs so maybe I'll add some more later.

**Comment by scosman** [comment]
Thanks for feedback! Some questions/comments inline. If any of these still repo on main we should split out separate issues for each.

> Resetting the password broke at some point as the amr token didn't seem to be set.

Is this still an issue? There were some fixes in this space, and I can't repo on saasstarter.work (which runs on main)

> Supabase auth has some updates that spam warnings when using the getsession method on the server side https://github.com/supabase/auth-js/issues/873. Should be fixed in a new version now.

Yup, pending fix here, but blocked on supabase: https://github.com/CriticalMoments/CMSaasStarter/pull/63

> Discounts. Applying discounts is a common thing but not trivial with the current pricing scheme system (as far as we could see)

I can see that being helpful. If someone wants to add it in a clean way I'm all for it, but also something folks can add on in their fork. There are a lot of ways to price, so I think we really are a "starter" more than an everything solution.

> Company name and website name should be optional when creating an account

Makes sense, but folks can just delete that. Again, the joys of being a template.

> We switched most forms to using superforms to make validation a bit clearer on the DX side (particularly for optional elements)

Yeah, I home brewed this and something like superforms seems better. Another change I'd take if someone wanted to take a run at it!


I won't leave this issue open since it covers a lot of topics and is hard to action on. The one bug I can repo is covered in an existing PR/Issue. If the amr/password-reset issue persists, please file a dedicated issue on that with some more details. I can't repo as is.

Thanks!
